apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: terraform-2022w11
  region: us-west-1
fargateProfiles:
- name: hobbit
  selectors:
  - labels:
      app: hobbit
    namespace: hobbits
  podExecutionRoleARN: arn:aws:iam::042617493216:role/cluster-terraform-fargateRole
  subnets:
  - subnet-0df1d03aba7faef75
  - subnet-022c99d5c3f591676
