apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 69dd939498054a211c3461b2a9cc8d26
    kubernetes.io/config.mirror: 69dd939498054a211c3461b2a9cc8d26
    kubernetes.io/config.seen: "2022-03-30T22:06:09.663744307Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2022-03-30T22:06:13Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-kind-control-plane
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: kind-control-plane
    uid: 45ef78ab-0d5b-4afe-90a4-91f40a24a451
  resourceVersion: "500"
  uid: 3eac5674-dd36-44ae-9027-21412a1ebf14
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --port=0
    image: k8s.gcr.io/kube-scheduler:v1.21.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-30T22:06:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-30T22:06:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-30T22:06:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-30T22:06:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://682ca2bd58a0f5b9aaa6ab7475fbad763eba810b1e2334167dfe4478de38631d
    image: k8s.gcr.io/kube-scheduler:v1.21.1
    imageID: sha256:1248d2d503d37429342d5e994559f8559f35d80a31b224d4db5324816fff7206
    lastState: {}
    name: kube-scheduler
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-30T22:05:50Z"
  hostIP: 172.18.0.2
  phase: Running
  podIP: 172.18.0.2
  podIPs:
  - ip: 172.18.0.2
  qosClass: Burstable
  startTime: "2022-03-30T22:06:13Z"
